modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "ftbteamskyblock"
version = "${version}"
displayName = "FTB Team Skyblock"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.ftbteamskyblock]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbteamskyblock]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbteamskyblock]]
modId = "architectury"
type = "required"
versionRange = "[13.0.6,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "ftbteamskyblock.mixins.json"
